from enum import Enum

class StavObjednavky(Enum):
    VYTVORENA = "VYTVORENA"
    CAKA_NA_POTVREDNIE = "CAKA_NA_POTVREDNIE"
    POTVRDENA = "POTVRDENA"
    ZRUSENA = "ZRUSENA"
    SPRACUVAVA_SA = "SPRACUVAVA_SA"
    DOKONCENA = "DOKONCENA"
    VYHODNOTENA = "VYHODNOTENA"
